# Generated by Django 6.0 on 2026-05-26 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('train_cutoff', models.DateTimeField()),
                ('val_cutoff', models.DateTimeField()),
                ('mining_run_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('family_assignments', models.JSONField(blank=True, default=dict)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelevanceLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_market_id', models.CharField(db_index=True, max_length=160)),
                ('candidate_market_id', models.CharField(db_index=True, max_length=160)),
                ('event_family', models.CharField(blank=True, db_index=True, max_length=160)),
                ('relevance', models.PositiveSmallIntegerField(choices=[(0, 'unrelated'), (1, 'weak'), (2, 'related'), (3, 'strong')], db_index=True)),
                ('negative_kind', models.CharField(blank=True, choices=[('positive', 'positive'), ('hard', 'hard negative'), ('easy', 'easy negative'), ('', 'unspecified')], db_index=True, default='', max_length=16)),
                ('max_xcorr', models.FloatField(default=0.0)),
                ('best_lag_seconds', models.IntegerField(default=0)),
                ('granger_p', models.FloatField(blank=True, null=True)),
                ('shock_co_fraction', models.FloatField(default=0.0)),
                ('source_first_seen', models.DateTimeField(blank=True, null=True)),
                ('candidate_first_seen', models.DateTimeField(blank=True, null=True)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('mining_cutoff', models.DateTimeField(db_index=True)),
                ('mining_run_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_family', 'relevance'], name='ranker_label_fam_rel_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_market_id', 'candidate_market_id', 'mining_run_id'), name='ranker_relevance_label_pair_run_unique')],
            },
        ),
        migrations.CreateModel(
            name='RerankerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(db_index=True, max_length=80)),
                ('kind', models.CharField(choices=[('training', 'training run'), ('inference', 'inference / baseline run'), ('probe', 'forecasting probe')], db_index=True, default='inference', max_length=16)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('artifact_path', models.CharField(blank=True, max_length=300)),
                ('mlflow_run_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('split', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='ranker.temporalsplit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['method', 'kind'], name='ranker_run_method_kind_idx')],
            },
        ),
        migrations.CreateModel(
            name='RankingExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_name', models.CharField(choices=[('train', 'train'), ('val', 'val'), ('test', 'test')], db_index=True, max_length=8)),
                ('source_market_id', models.CharField(db_index=True, max_length=160)),
                ('event_family', models.CharField(blank=True, db_index=True, max_length=160)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='ranker.temporalsplit')),
            ],
            options={
                'ordering': ['split_name', 'source_market_id'],
                'indexes': [models.Index(fields=['split', 'split_name'], name='ranker_example_split_idx')],
            },
        ),
    ]
