# Generated by Django 5.2.12 on 2026-03-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphrun',
            name='event_slug',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='graphrun',
            name='graph_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='graphrun',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
