# Generated by Django 5.2.12 on 2026-03-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_graphrun_event_slug_graphrun_graph_stats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('thesis', models.CharField(max_length=240)),
                ('summary', models.TextField(blank=True)),
                ('cadence', models.CharField(blank=True, max_length=80)),
                ('items', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
