# Generated by Django 5.2.12 on 2026-03-11 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('dataset_version', models.CharField(blank=True, max_length=80)),
                ('code_version', models.CharField(blank=True, max_length=80)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('artifacts', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(default='completed', max_length=32)),
                ('detail', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('token_input', models.PositiveIntegerField(default=0)),
                ('token_output', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('graph_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_traces', to='web.graphrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('event_slug', models.CharField(db_index=True, max_length=300)),
                ('event_title', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(default='open', max_length=32)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('source_kind', models.CharField(blank=True, max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('implied_probability', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('liquidity', models.FloatField(default=0.0)),
                ('open_interest', models.FloatField(default=0.0)),
                ('related_market_count', models.PositiveIntegerField(default=0)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('snapshot_at', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('graph_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='web.graphrun')),
            ],
            options={
                'ordering': ['-snapshot_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResolutionLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_slug', models.CharField(db_index=True, max_length=300)),
                ('resolved_outcome', models.CharField(max_length=120)),
                ('resolved_probability', models.FloatField(default=0.0)),
                ('source', models.CharField(default='outcome_prices', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market_snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_label', to='web.marketsnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
