# Generated by Django 5.2.12 on 2026-03-11 20:56

from django.db import migrations


WATCHLISTS = [
    {
        "slug": "macro-rate-spillover",
        "title": "Macro Rate Spillover",
        "thesis": "Track how Fed path repricing spreads into inflation, USD, and adjacent macro contracts.",
        "summary": "Built for traders who want one starting point for rates, inflation, dollar strength, and second-order market reactions.",
        "cadence": "Daily",
        "items": [
            {
                "label": "Fed decision in March",
                "url": "https://polymarket.com/event/fed-decision-in-march-885",
                "note": "Anchor market for near-term monetary-policy repricing.",
            },
            {
                "label": "How many Fed rate cuts in 2026?",
                "url": "https://polymarket.com/event/how-many-fed-rate-cuts-in-2026",
                "note": "Longer-duration spillover from the same macro narrative.",
            },
            {
                "label": "Largest company end of March?",
                "url": "https://polymarket.com/event/largest-company-end-of-march",
                "note": "Equity sentiment beneficiary when rates reprice growth and tech exposure.",
            },
        ],
    },
    {
        "slug": "commodity-shock-watch",
        "title": "Commodity Shock Watch",
        "thesis": "Monitor crude, inflation, and downstream macro spillover from a single commodity catalyst.",
        "summary": "Useful when one crude headline can propagate into inflation expectations, growth fears, and correlated contracts.",
        "cadence": "Daily",
        "items": [
            {
                "label": "Crude oil by end of March",
                "url": "https://polymarket.com/event/will-crude-oil-hit-80-by-end-of-march",
                "note": "Primary commodity trigger market.",
            },
            {
                "label": "Will Crude Oil (CL) hit by end of March?",
                "url": "https://polymarket.com/event/will-crude-oil-cl-hit-end-of-march",
                "note": "Settlement-sensitive variant worth comparing for narrative drift.",
            },
            {
                "label": "CPI path / inflation-linked market",
                "url": "https://polymarket.com/event/will-cpi-come-in-above-expectations-next-release",
                "note": "Use as downstream macro confirmation when energy reprices inflation.",
            },
        ],
    },
    {
        "slug": "political-narrative-cluster",
        "title": "Political Narrative Cluster",
        "thesis": "Watch a nomination or election market together with coalition, turnout, and media-proxy contracts.",
        "summary": "Designed for politics traders who need a narrative-first watchlist instead of browsing isolated contracts.",
        "cadence": "Weekly",
        "items": [
            {
                "label": "Democratic nominee 2028",
                "url": "https://polymarket.com/event/democratic-nominee-2028",
                "note": "Anchor market for coalition shifts and adjacent candidate narratives.",
            },
            {
                "label": "Election media or debate catalyst",
                "url": "https://polymarket.com/event/will-there-be-a-presidential-debate",
                "note": "Catalyst proxy for narrative acceleration.",
            },
            {
                "label": "Turnout or battleground market",
                "url": "https://polymarket.com/event/will-democrats-win-the-popular-vote-2028",
                "note": "Second-order expression of campaign momentum.",
            },
        ],
    },
]


def seed_watchlists(apps, schema_editor):
    Watchlist = apps.get_model("web", "Watchlist")
    for item in WATCHLISTS:
        Watchlist.objects.update_or_create(
            slug=item["slug"],
            defaults={
                "title": item["title"],
                "thesis": item["thesis"],
                "summary": item["summary"],
                "cadence": item["cadence"],
                "items": item["items"],
                "is_featured": True,
            },
        )


def unseed_watchlists(apps, schema_editor):
    Watchlist = apps.get_model("web", "Watchlist")
    Watchlist.objects.filter(slug__in=[item["slug"] for item in WATCHLISTS]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_experimentrun_agenttrace_marketsnapshot_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_watchlists, unseed_watchlists),
    ]
