# Generated by Django 5.2.12 on 2026-03-13 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_crossvenuemarketmap_leadlagpair_marketeventtick_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedMarketJudgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_key', models.CharField(max_length=300)),
                ('candidate_title', models.CharField(max_length=300)),
                ('candidate_summary', models.TextField(blank=True)),
                ('candidate_source_url', models.URLField(blank=True)),
                ('candidate_rank', models.PositiveIntegerField(default=0)),
                ('candidate_confidence', models.FloatField(default=0.0)),
                ('usefulness_label', models.CharField(db_index=True, default='watch', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('reviewer', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(default='manual-web', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graph_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_market_judgments', to='web.graphrun')),
            ],
            options={
                'ordering': ['-updated_at', 'candidate_rank', 'candidate_title'],
                'constraints': [models.UniqueConstraint(fields=('graph_run', 'candidate_key'), name='web_related_market_judgment_unique')],
            },
        ),
    ]
