# Generated by Django 5.2.12 on 2026-03-17 21:55

from django.db import migrations


UPDATED_SUMMARIES = {
    "macro-rate-spillover": "Built for macro research on rates, inflation, dollar strength, and second-order market reactions.",
    "political-narrative-cluster": "Designed for narrative-first political research instead of browsing isolated contracts.",
}

PREVIOUS_SUMMARIES = {
    "macro-rate-spillover": "Built for traders who want one starting point for rates, inflation, dollar strength, and second-order market reactions.",
    "political-narrative-cluster": "Designed for politics traders who need a narrative-first watchlist instead of browsing isolated contracts.",
}


def refresh_watchlist_copy(apps, schema_editor):
    Watchlist = apps.get_model("web", "Watchlist")
    for slug, summary in UPDATED_SUMMARIES.items():
        Watchlist.objects.filter(slug=slug).update(summary=summary)


def restore_watchlist_copy(apps, schema_editor):
    Watchlist = apps.get_model("web", "Watchlist")
    for slug, summary in PREVIOUS_SUMMARIES.items():
        Watchlist.objects.filter(slug=slug).update(summary=summary)


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_relatedmarketjudgment_multi_reviewer"),
    ]

    operations = [
        migrations.RunPython(refresh_watchlist_copy, restore_watchlist_copy),
    ]
